gText_Birch_Welcome::
	.string "BadIntroText\p"
	.string "$"

gText_Birch_Pokemon::
	.string ".\p"
	.string "$"

gText_Birch_MainSpeech::
	.string ".\p"
	.string "$"

gText_Birch_AndYouAre::
	.string ".$"

gText_Birch_BoyOrGirl::
	.string ".$"

gText_Birch_WhatsYourName::
	.string ".$"

gText_Birch_SoItsPlayer::
	.string ".$"

gText_Birch_YourePlayer::
	.string ".$"

gText_Birch_AreYouReady::
	.string ".$"
