CelesticTown_Ruins_MapScripts::
	.byte 0


CelesticTown_Ruins_TriggerScript_Intro::
# 6 "data/maps/CelesticTown_Ruins/scripts.pory"
	lockall
# 7 "data/maps/CelesticTown_Ruins/scripts.pory"
	msgbox CelesticTown_Ruins_TriggerScript_Intro_Text_0
# 8 "data/maps/CelesticTown_Ruins/scripts.pory"
	releaseall
	return


CelesticTown_Ruins_TriggerScript_Intro_Text_0:
# 7 "data/maps/CelesticTown_Ruins/scripts.pory"
	.string "Cynthia gazes at ruins$"
